spring:
  application:
    name: my-pocket-api
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        
# Gera o SQL no arquivo create.sql na pasta raiz do projeto
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
